#include "InscriereRepository.h"
#include "ConectorBazaDate.h"
#include "ExceptieEdu.h"
#include <limits>
namespace { void idValid(int id,const char* nume){if(id<=0)throw ExceptieEdu(std::string(nume)+" trebuie sa fie strict pozitiv.");} int idDin(const std::string& s){try{std::size_t n=0;long long x=std::stoll(s,&n);if(n!=s.size()||x<=0||x>std::numeric_limits<int>::max())throw 0;return static_cast<int>(x);}catch(...){throw ExceptieEdu("Id invalid citit din baza de date.");}} }
InscriereRepository::InscriereRepository(ConectorBazaDate& c):conector(c){}
void InscriereRepository::valideazaStudent(int id){idValid(id,"Id-ul studentului");const auto r=conector.executaSelectParametrizat("SELECT u.id FROM utilizatori u JOIN studenti s ON s.utilizator_id=u.id WHERE u.id=? AND u.rol='student';",{std::to_string(id)});if(r.empty())throw ExceptieEdu("Studentul specificat nu exista sau rolul este invalid.");}
void InscriereRepository::valideazaCurs(int id){idValid(id,"Id-ul cursului");if(conector.executaSelectParametrizat("SELECT id FROM cursuri WHERE id=?;",{std::to_string(id)}).empty())throw ExceptieEdu("Cursul specificat nu exista.");}
void InscriereRepository::inscrieStudentLaCurs(int s,int c){valideazaStudent(s);valideazaCurs(c);if(esteInscris(s,c))throw ExceptieEdu("Studentul este deja inscris la curs.");conector.executaInterogareParametrizata("INSERT INTO inscrieri_curs (curs_id,student_id) VALUES (?,?);",{std::to_string(c),std::to_string(s)});}
void InscriereRepository::retrageStudentDeLaCurs(int s,int c){valideazaStudent(s);valideazaCurs(c);if(conector.executaInterogareParametrizata("DELETE FROM inscrieri_curs WHERE curs_id=? AND student_id=?;",{std::to_string(c),std::to_string(s)})==0)throw ExceptieEdu("Inscrierea specificata nu exista.");}
bool InscriereRepository::esteInscris(int s,int c){valideazaStudent(s);valideazaCurs(c);return !conector.executaSelectParametrizat("SELECT 1 FROM inscrieri_curs WHERE curs_id=? AND student_id=?;",{std::to_string(c),std::to_string(s)}).empty();}
std::vector<CursInregistrare> InscriereRepository::listeazaCursuriStudent(int s){valideazaStudent(s);std::vector<CursInregistrare> v;for(const auto&r:conector.executaSelectParametrizat("SELECT c.id,c.nume,c.parinte_id,c.proprietar_id FROM cursuri c JOIN inscrieri_curs i ON i.curs_id=c.id WHERE i.student_id=? ORDER BY c.id;",{std::to_string(s)})){v.push_back({idDin(r[0]),r[1],r[2].empty()?std::nullopt:std::optional<int>(idDin(r[2])),idDin(r[3])});}return v;}
std::vector<CursInregistrare> InscriereRepository::listeazaCursuriDisponibile(int s){valideazaStudent(s);std::vector<CursInregistrare> v;for(const auto&r:conector.executaSelectParametrizat("SELECT c.id,c.nume,c.parinte_id,c.proprietar_id FROM cursuri c WHERE NOT EXISTS (SELECT 1 FROM inscrieri_curs i WHERE i.curs_id=c.id AND i.student_id=?) ORDER BY c.id;",{std::to_string(s)})){v.push_back({idDin(r[0]),r[1],r[2].empty()?std::nullopt:std::optional<int>(idDin(r[2])),idDin(r[3])});}return v;}
std::vector<UtilizatorInregistrare> InscriereRepository::listeazaStudentiCurs(int c){valideazaCurs(c);std::vector<UtilizatorInregistrare> v;for(const auto&r:conector.executaSelectParametrizat("SELECT u.id,u.email,u.parola,u.rol FROM utilizatori u JOIN inscrieri_curs i ON i.student_id=u.id WHERE i.curs_id=? ORDER BY u.id;",{std::to_string(c)})){v.push_back({idDin(r[0]),r[1],r[2],r[3]});}return v;}
